openapi: 3.0.0
info:
  title: paymentchain-transaction microservice
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/transactions
    description: common path
paths:
  /transaction/operationtp:
    post:
      summary: Transferir o Pagar
      operationId: operationTP
      requestBody:
        $ref: "#/components/requestBodies/TransactionTpDTO"
      responses:
        201:
          description: todo bien
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    TransactionTPDTO:
      type: object
      properties:
        iban:
          type: string
          nullable: false
          minLength: 1
        paymentOperation:
          enum:
            - DEPOSITAR
            - RETIRAR
            - TRANSFERIR
            - PAGAR
          nullable: false
        amount:
          type: number
          nullable: false
          minimum: 5
        description:
          type: string
          nullable: false
          minLength: 1
        destination:
          type: string
          nullable: false
          minLength: 1
  requestBodies:
    TransactionTpDTO:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/TransactionTPDTO"



